### ISSUE TITLE
Test result was not reported by test-runner

### ISSUE THREAD

**Issue by fabiosalamone** [SpoonLabs/flacoco#179]
Hi, I'm trying to execute Flacoco from CLI on the project Closure 152 downloaded from [Defects4J](https://github.com/rjust/defects4j).

Before running Flacoco, I've built the Closure 152 project using the command `ant jar` (as written in its readme file) and ran the JUnit tests with Eclipse.
[Here](https://pastebin.com/sU5eUSVg) is the tree of the folder after those operations.

When I launch Flacoco from the CLI with the command 
```
java -jar target/flacoco-1.0.3-SNAPSHOT-jar-with-dependencies.jar  
--binJavaDir /home/except/Desktop/download_bugs/Closure/152/build/classes/ 
--binTestDir /home/except/Desktop/download_bugs/Closure/152/build/test-classes 
--srcJavaDir /home/except/Desktop/download_bugs/Closure/152/src/ 
--srcTestDir /home/except/Desktop/download_bugs/Closure/152/test 
-o /home/except/Desktop/download_bugs/Closure/152/flacoco.csv
```
The output is `WARN CoverageRunner - Test [Manual]TestMethod="TestName" result was not reported by test-runner.` repeated hundreds of times.  At the end of the execution I got 
```
INFO CoverageRunner - Tests found: 8092
INFO CoverageRunner - Tests executed: 4994
```

When I run JUnit in Eclipse, 6199 tests are performed. What I'm doing wrong? I attach some screenshots.

![image](https://user-images.githubusercontent.com/59093291/164008071-aba918fe-a6ff-4a09-b5cf-bf92e3bd98fb.png)

![image](https://user-images.githubusercontent.com/59093291/164007943-15200b65-1745-4582-a0db-856bf8e8c339.png)

**Comment by andre15silva** [comment]
Hi @fabiosalamone 

Identifying which tests to run, and then actually running them, is a hard task.

When you execute the unit tests through Eclipse you are using Eclipse's test detection mechanisms (which are different from the ones Flacoco uses) hence the difference in the number of tests found.

Execution wise, again, we face the same issue. Somes, test-runner (the library we use to execute JUnit tests) is not able to execute them.

So you are not doing anything wrong, the problem is on Flacoco's side.
